//auto generated by seu-yacc
#ifndef _TABLE_H
#define _TABLE_H


#define  36
#define ASSIGN 14
#define COMMA 16
#define DIVIDE 21
#define DOT 17
#define ELSE 5
#define EQUAL 22
#define FLOAT 1
#define IF 4
#define INT 0
#define LBRACE 10
#define LBRACK 12
#define LOW 43
#define LPAR 8
#define MINUS 19
#define NAME 2
#define NUMBER 7
#define PLUS 18
#define RBRACE 11
#define RBRACK 13
#define RETURN 6
#define RPAR 9
#define SEMICOLON 15
#define STRUCT 3
#define TIMES 20
#define UMINUS 44
#define _LR_END 45
#define block 39
#define declaration 35
#define declarations 34
#define exp 25
#define exps 29
#define field 30
#define fields 32
#define fun_declaration 37
#define lexp 26
#define more_parameters 28
#define parameter 24
#define parameters 27
#define program 33
#define program_LR 46
#define statement 42
#define statements 41
#define type 23
#define var 31
#define var_declaration 38
#define var_declarations 40

#endif
